[package]
name = "chip8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.14.0"
eframe = "0.19.0"
egui = "0.19.0"
rand = "0.8.5"
rand_pcg = "0.3.1"
rfd = "0.10.0"
spin_sleep = "1.1.1"
